### ISSUE TITLE
Consider the time column in the time slice method

### ISSUE THREAD

**Issue by SamVanhoutte** [arcus-azure/arcus.ml#50]
The signature of the time_slice contains a time_column , which is ignored and it's just assumed that the dataframe contains a DateTimeIndex.  
Check should be so that if there is no DateTimeIndex, there should be one created, using that column.
```python
def time_slice(df: pd.DataFrame, time_column:str, start: datetime.datetime = None, end: datetime.datetime = None):
```

**Comment by stijnmoreels** [comment]
I think this is already taken into account here: https://github.com/arcus-azure/arcus.ml/blob/259b071acca12d756b505926a44b685e556395a3/arcus/ml/timeseries/timeops.py#L51.

**Comment by SamVanhoutte** [comment]
Agreed.
