### ISSUE TITLE
Provide development guidance

### ISSUE THREAD

**Issue by SamVanhoutte** [arcus-azure/arcus.ml#98]
As commented by @stijnmoreels in #96 , it is needed to have better developer documentation.

Developer documentation:
- Link to PyPi feed
- Link to how to set such a virtual environment

Build documentation
- This is a good first draft of the build process, but I think we need some work here. The steps describe an abstracted task, but are missing maybe the actual commends/low-level steps one has to take. Keep in mind that we should be accessible for both beginner/advanced developers.

**Comment by SamVanhoutte** [comment]
@stijnmoreels : I believe this one can be closed?

**Comment by stijnmoreels** [comment]
> @stijnmoreels : I believe this one can be closed?

Yes, I think so. We can always improve upon the current set of docs. Thx for this!
